apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: yelhadad/shopping-prod
      context: server
      docker:
        dockerfile: Dockerfile
    - image: yelhadad/shopping-client-prod
      context: client
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./k8s/*
