apiVersion: v1
kind: PersistentVolume
metadata:
  name: shopping-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.138.0.2
    path: "/var/nfs/general"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-nfs-pvc
spec: 
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi 

