apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping-app
          image: yelhadad/shopping-prod
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: shopping-config-map
                  key: DBNAME
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: shopping-config-map
                  key: HOST
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: shopping-config-map
                  key: USER
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: shopping-config-map
                  key: PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: flask
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-srv
spec:
  selector:
    app: shopping
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
